local Battle = require 'main.battle.battle'
local Combatant = require 'main.combatant.combatant'

local battle_url = 'main:/battle#battle'

local enemy_combatants = {
    {prototype='ranged', position=vmath.vector3(600, 200, 0)},
    {prototype='normal', position=vmath.vector3(500, 100, 0)},
    {prototype='tough', position=vmath.vector3(600, 50, 0)},
    {prototype='tough', position=vmath.vector3(600, 0, 0)},
    {prototype='tough', position=vmath.vector3(600, 20, 0)},
    {prototype='ranged', position=vmath.vector3(600, -50, 0)},
    {prototype='tough', position=vmath.vector3(600, 50, 0)},
    {prototype='tough', position=vmath.vector3(600, 0, 0)},
    {prototype='tough', position=vmath.vector3(600, 20, 0)},
    {prototype='tough', position=vmath.vector3(600, -50, 0)},
    {prototype='tough', position=vmath.vector3(500, 50, 0)},
    {prototype='ranged', position=vmath.vector3(500, 0, 0)},
    {prototype='tough', position=vmath.vector3(500, 20, 0)},
    {prototype='tough', position=vmath.vector3(500, -50, 0)},
    {prototype='tough', position=vmath.vector3(500, 50, 0)},
    {prototype='tough', position=vmath.vector3(500, 0, 0)},
    {prototype='tough', position=vmath.vector3(500, 20, 0)},
    {prototype='tough', position=vmath.vector3(500, -50, 0)},
    {prototype='normal', position=vmath.vector3(500, -100, 0)},
    {prototype='ranged', position=vmath.vector3(600, -200, 0)},
}

local player_combatants = {
    {prototype='normal', position=vmath.vector3(-500, 200, 0)},
    {prototype='normal', position=vmath.vector3(-500, 100, 0)},
    {prototype='normal', position=vmath.vector3(-520, 0, 0)},
    {prototype='normal', position=vmath.vector3(-480, -100, 0)},
    {prototype='normal', position=vmath.vector3(-500, -200, 0)},
    {prototype='normal', position=vmath.vector3(-550, -200, 0)},
    {prototype='normal', position=vmath.vector3(-500, -200, 0)},
    {prototype='ranged', position=vmath.vector3(-600, -100, 0)},
    {prototype='normal', position=vmath.vector3(-500, -100, 0)},
    {prototype='normal', position=vmath.vector3(-600, 0, 0)},
    {prototype='ranged', position=vmath.vector3(-550, 0, 0)},
    {prototype='normal', position=vmath.vector3(-500, 0, 0)},
    {prototype='normal', position=vmath.vector3(-600, 100, 0)},
    {prototype='ranged', position=vmath.vector3(-550, 100, 0)},
    {prototype='normal', position=vmath.vector3(-500, 100, 0)},
    {prototype='normal', position=vmath.vector3(-550, 200, 0)},
    {prototype='ranged', position=vmath.vector3(-500, 200, 0)},
    {prototype='normal', position=vmath.vector3(-600, 100, 0)},
    {prototype='normal', position=vmath.vector3(-500, 100, 0)},
    {prototype='normal', position=vmath.vector3(-600, 200, 0)},
    {prototype='ranged', position=vmath.vector3(-550, 200, 0)},
    {prototype='normal', position=vmath.vector3(-500, 200, 0)},
    {prototype='normal', position=vmath.vector3(-600, 100, 0)},
    {prototype='normal', position=vmath.vector3(-550, 100, 0)},
    {prototype='normal', position=vmath.vector3(-500, 100, 0)},
    {prototype='normal', position=vmath.vector3(-600, 200, 0)},
    {prototype='normal', position=vmath.vector3(-550, 200, 0)},
    {prototype='normal', position=vmath.vector3(-500, 200, 0)},
}
local set_combatants = function()
    for i, v in ipairs(player_combatants) do
        Battle.add_combatant(v.prototype, 'player', v.position)
    end
    for i, v in ipairs(enemy_combatants) do
        Battle.add_combatant(v.prototype, 'enemy', v.position)
    end
    msg.post(battle_url, 'set_combatants')
end

function init(self)
    set_combatants()
end

function update(self, dt)
    Battle.tick_combat(dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash('start_combat') then Battle.start_combat() end
end