local utils = require 'main.utils.basic_utils'
local bars = require 'main.utils.bars'
local Combatant = require 'main.combatant.combatant'
local Battle = require 'main.battle.battle'
local Player = require 'main.player.player'
local Enemy = require 'main.enemy.enemy'
local urls = require 'main.urls'

local M
M = {
	display = {},
	get_display = function(id) return utils.search(M.display, function(v) return v.id == id end) end,
	add_combatant = function(combatant)
		local combatant_data = Combatant.get_data(combatant.prototype)
		local template = gui.get_node('combatant_template/node')
		local tree = gui.clone_tree(template)
		local node = tree['combatant_template/node']
		local hp_bar = tree['combatant_template/hp']
		local hp_bar_fill = tree['combatant_template/hp_fill']
		local bar = bars.new(hp_bar, hp_bar_fill, nil, combatant.hp, combatant.max_hp)
		if combatant.hp == combatant.max_hp then bar.hide() end
		table.insert(M.display, {id=combatant.id, node=node, bar=bar})

		gui.set_id(node, combatant.id)
		gui.set_position(node, combatant.position)
		if combatant.team == 'enemy' then gui.set_color(node, vmath.vector4(0.7,0.7,0.7, 1)) end
		
		gui.set_texture(node, 'combatants')
		if combatant_data.idle_animation and pcall(gui.play_flipbook, node, combatant_data.idle_animation) then
			gui.play_flipbook(node, combatant_data.idle_animation)
		end
		if hash(combatant.team) == hash('player') then M.update_z() end
	end,
	move_combatant = function(combatant)
		local node = gui.get_node(combatant.id)
		gui.set_position(node, combatant.position)
	end,
	set_combatant_facing = function(combatant)
		local display = M.get_display(combatant.id)
		local node = display.node
		local bar = display.bar
		if hash(combatant.facing) == hash('right') then
			local euler = 0
			gui.set(node, 'euler.y', euler)
			gui.set(bar.node, 'euler.y', euler)
		elseif hash(combatant.facing) == hash('left') then
			local euler = 180
			gui.set(node, 'euler.y', euler)
			gui.set(bar.node, 'euler.y', euler)
		end
	end,
	defeat_combatant = function(combatant)
		local node = gui.get_node(combatant.id)
		gui.delete_node(node)
	end,
	remove_combatant = function(combatant)
		local node = gui.get_node(combatant.id)
		gui.delete_node(node)
	end,
	cancel_combatant_attack = function(combatant)
		local combatant_data = Combatant.get_data(combatant.prototype)
		local node = gui.get_node(combatant.id)
		gui.cancel_flipbook(node)
		gui.play_flipbook(node, combatant_data.idle_animation)
	end,
	show_combatant_attack = function(combatant)
		local combatant_data = Combatant.get_data(combatant.prototype)
		local initial_target = combatant.target
		local node = gui.get_node(combatant.id)
		local defender = Battle.get_combatant(combatant.target)
		if not defender or defender.hp <= 0 then return end
		if combatant_data.attack_animation then
			gui.play_flipbook(node, combatant_data.attack_animation, function()
				gui.play_flipbook(node, combatant_data.idle_animation)
			end)
			if combatant_data.is_ranged then
				local defender_node = gui.get_node(combatant.target)
				local target_position = gui.get_position(defender_node)
				timer.delay(combatant_data.projectile_launch_delay, false, function()
					local attacker_now = Battle.get_combatant(combatant.id)
					if not attacker_now or not defender
						or attacker_now.hp <=0 or defender.hp <= 0
						or hash(attacker_now.state) ~= hash('attacking')
						or defender.id ~= initial_target then
							return
					end
					local offset = target_position - combatant.position
					local angle = math.atan2(offset.y, offset.x)
					local rotation = vmath.quat_rotation_z(angle)
					if pcall(gui.get_position, defender_node) then target_position = gui.get_position(defender_node) end
					local projectile_node = gui.new_box_node(vmath.vector3(), vmath.vector3(30))
					gui.set_rotation(projectile_node, rotation)
					gui.set_texture(projectile_node, 'combatants')
					gui.play_flipbook(projectile_node, combatant_data.projectile_animation)
					local duration = vmath.length(offset)/combatant_data.projectile_speed
					gui.set_parent(projectile_node, gui.get_node('map'))
					gui.set_position(projectile_node, combatant.position)
					gui.animate(projectile_node, 'position', target_position, gui.EASING_LINEAR, duration, 0, function()
						gui.delete_node(projectile_node)
					end)
				end)
			end
		end
	end,
	take_dmg = function(combatant, dmg)
		local display = M.get_display(combatant.id)
		local node = display.node
		if combatant.hp ~= combatant.max_hp then display.bar.show() end
		display.bar.set_fill(combatant.hp)
		local euler = 10
		gui.cancel_animations(node, 'euler.z')
		gui.set(node, 'euler.z', euler)
		gui.animate(node, 'euler.z', 0, gui.EASING_INCUBIC, 0.1)

	end,
	update_z = function()
		local nodes = {}
		for i, v in ipairs(Battle.combatants) do
			local node = gui.get_node(v.id)
			local position = gui.get_position(node)
			table.insert(nodes, {node=node, y=position.y})
		end
		table.sort(nodes, function(a, b) return a.y > b.y end)
		for i = 2, #nodes do
			gui.move_above(nodes[i].node, nodes[i-1].node)
		end
	end
}

local set_enemies = function()
	local enemy_party = Enemy.get_random_party(Player.day)
	for i, v in ipairs(enemy_party) do
		v.facing = 'left'
		Battle.add_combatant(v)
		M.add_combatant(v)
		M.set_combatant_facing(v)
	end
	M.update_z()
end

function init(self)
	set_enemies()

	-- increase timescale for testing
	msg.post(urls.battle, 'set_time_step', {factor = 3, mode=0})
end

function update(selt, dt)
	if Battle.combat_started then M.update_z() end
	Battle.tick_combat(dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash('combatant_added') then
		M.add_combatant(message.combatant)
	elseif message_id == hash('combatant_removed') then
		M.remove_combatant(message.combatant)
	elseif message_id == hash('combatant_moved') then
		M.move_combatant(message.combatant)
	elseif message_id == hash('combatant_facing') then
		M.set_combatant_facing(message.combatant)
	elseif message_id == hash('combatant_attacked') then
		M.show_combatant_attack(message.combatant)
	elseif message_id == hash('combatant_attack_cancelled') then
		M.cancel_combatant_attack(message.combatant)
	elseif message_id == hash('combatant_defeated') then
		M.defeat_combatant(message.combatant)
	elseif message_id == hash('combatant_took_dmg') then
		M.take_dmg(message.combatant, message.dmg)
	elseif message_id == hash('start_combat') then
		Battle.start_combat()
	end
end