local utils = require 'main.utils.basic_utils'
local bars = require 'main.utils.bars'
local gui_module = require 'main.utils.gui_module'
local mygui
local gui_utils = require 'main.utils.gui_utils'
local urls = require 'main.urls'

local Unit = require 'main.unit.unit'
local Battle = require 'main.battle.battle'

local Player = require 'main.player.player'

local Deployment, Map

Map = {
	display = {},
	init = function(self)
		local map_node = gui.get_node('map')
		local deployment_zone_node = gui.get_node('deployment_zone')
		local button = mygui.create_button(map_node, function(params)
			if #Deployment.to_deploy == 0 then return end
			local unit = utils.search(Player.party, function(v) return v.id == Deployment.active_id end) assert(unit)
			local unit_data = Unit.get_data(unit.prototype)

			-- restrict placement to deployment_zone
			if not gui.pick_node(deployment_zone_node, params.x, params.y) then return end

			-- enforce unit collision radius
			local position = vmath.vector3(params.x, params.y, 0)
			position = position - gui_utils.get_absolute_position(map_node)
			local closest_unit, closest_distance_sq = Battle.get_closest_unit(position)
			pprint(closest_unit, closest_distance_sq)
			if closest_unit then
				local closest_unit_data = Unit.get_data(closest_unit.prototype)
				if closest_distance_sq < (closest_unit_data.radius + unit_data.radius)^2 then return end
			end
			
			Deployment:place_unit(Deployment.active_id, position)
		end)
	end,
}

Deployment = {
	to_deploy = {},
	display = {},
	stance = '',
	active_display = {},
	init = function(self)
		local active_unit = Player.party[1]
		self.active_id = active_unit.id
		self.active_display.bar = bars.new(gui.get_node('active_unit_hp'), gui.get_node('active_unit_hp_fill'), nil, active_unit.hp, active_unit.max_hp)
		for i, v in ipairs(Player.party) do	table.insert(self.to_deploy, v)	end
		self:update_display()

		-- setup stance buttons
		local stance_aggressive_node = gui.get_node('button_aggressive')
		local stance_defensive_node = gui.get_node('button_defensive')
		local set_stance_aggressive = function()
			if hash(self.stance) == hash('aggressive') then return end
			self.stance = 'aggressive'
			gui.set_color(stance_aggressive_node, vmath.vector4(0.8, 0.4, 0.4, 1))
			gui.set_color(stance_defensive_node, vmath.vector4(1))
		end
		local set_stance_defensive = function()
			if hash(self.stance) == hash('defensive') then return end
			self.stance = 'defensive'
			gui.set_color(stance_aggressive_node, vmath.vector4(1))
			gui.set_color(stance_defensive_node, vmath.vector4(0.4, 0.4, 0.8, 1))
		end
		mygui.create_button(stance_aggressive_node, set_stance_aggressive)
		mygui.create_button(stance_defensive_node, set_stance_defensive)
		set_stance_aggressive()

		-- setup start combat button
		local start_button_node = gui.get_node('button_start')
		mygui.create_button(start_button_node, function()
			Battle.start_combat()
			self:close()
			msg.post(urls.battle_proxy, 'hide_stances')
		end)

		mygui.create_keybind({action_id = 'right_click', on_pressed=function() if Battle.combat_started then return end self:undo_place_unit() end})
	end,

	update_display = function(self)
		for i, v in ipairs(self.display) do gui.delete_node(v.node) end
		self.display = {}
		local active_i = utils.findIndex(self.to_deploy, self.active_id, 'id', 1)
		for i, unit in ipairs(self.to_deploy) do
			local unit_data = Unit.get_data(unit.prototype)
			if unit.id == self.active_id then
				-- render the active party member
				local art = gui.get_node('active_unit_art')
				gui.set_texture(art, 'units')
				gui_utils.set_texture_with_default_placeholder(art, 'units', unit.prototype..'_idle', '_placeholder')
				self.active_display.bar.set_max(unit.max_hp)
				self.active_display.bar.set_fill(unit.hp)
			else
				-- render the non-active party members on bar
				local template = gui.get_node('unit_card_template')
				local tree = gui.clone_tree(template)
				local node = tree.unit_card_template
				local art = tree.unit_card_template_art
				gui.set_texture(node, 'units')
				gui_utils.set_texture_with_default_placeholder(art, 'units', unit.prototype..'_idle', '_placeholder')
				local bar = bars.new(tree.unit_card_template_hp, tree.unit_card_template_hp_fill, nil, unit.hp, unit.max_hp)

				table.insert(self.display, {node=node, id=unit.id})
				local i_mod = 0 if active_i and i > active_i then i_mod = -1 end -- account for active_unit being pulled out of the bar
				local x = (i + i_mod) * 110
				gui.set_position(node, vmath.vector3(x, 0, 0))
				gui.set_parent(node, gui.get_node('units'))
			end
		end

		gui.set_enabled(gui.get_node('active_unit'), #self.to_deploy > 0)
	end,

	active_unit = nil,
	select_unit = function(self, id) self.active_id = id end,
	place_unit = function(self, id, position)
		local party_member = utils.search(self.to_deploy, function(v) return v.id == id end)
		party_member.position = position
		party_member.stance = self.stance
		Battle.add_unit(party_member)
		msg.post(urls.battle_proxy, 'unit_added', {unit = party_member})
		table.remove(self.to_deploy, 1)
		if #self.to_deploy > 0 then
			self.active_id = self.to_deploy[1].id
		else
			self.active_id = nil
		end
		self:update_display()
	end,
	undo_place_unit = function(self)
		local unit = Battle.undo_add_unit()
		if not unit then return end
		table.insert(self.to_deploy, 1, unit)
		self.active_id = unit.id
		self:update_display()
		msg.post(urls.battle_proxy, 'unit_removed', {unit = unit})
	end,
	close = function(self)
		gui.set_enabled(gui.get_node('root'), false)
		for i, v in ipairs(self.display) do gui.delete_node(v.node) end
	end
}

function init(self)
	msg.post(urls.battle, 'acquire_input_focus')
	msg.post('.', 'acquire_input_focus')
	mygui = gui_module.new(self, {})

	Map:init()
	Deployment:init()
end

function on_input(self, action_id, action)
	mygui.handle_input(action_id, action)
end
