local utils = require 'main.utils.basic_utils'
local bars = require 'main.utils.bars'
local gui_module = require 'main.utils.gui_module'
local mygui
local gui_utils = require 'main.utils.gui_utils'
local urls = require 'main.urls'

local Combatant = require 'main.combatant.combatant'
local Battle = require 'main.battle.battle'

local Player = require 'main.player.player'

local Deployment, Map

Map = {
	display = {},
	init = function(self)
		local map_node = gui.get_node('map')
		local deployment_zone_node = gui.get_node('deployment_zone')
		local button = mygui.create_button(map_node, function(params)
			if #Deployment.to_deploy == 0 then return end
			if not gui.pick_node(deployment_zone_node, params.x, params.y) then return end
			local position = vmath.vector3(params.x, params.y, 0)
			position = position - gui_utils.get_absolute_position(map_node)
			Deployment:place_combatant(Deployment.active_id, position)
		end)
	end,
}

Deployment = {
	to_deploy = {},
	display = {},
	active_display = {},
	init = function(self)
		local active_combatant = Player.party[1]
		self.active_id = active_combatant.id
		self.active_display.bar = bars.new(gui.get_node('active_combatant_hp'), gui.get_node('active_combatant_hp_fill'), nil, active_combatant.hp, active_combatant.max_hp)
		for i, v in ipairs(Player.party) do	table.insert(self.to_deploy, v)	end
		self:update_display()

		local start_button_node = gui.get_node('button_start')
		mygui.create_button(start_button_node, function()
			Battle.start_combat()
			self:close()
		end)

		mygui.create_keybind({action_id = 'right_click', on_pressed=function() self:undo_place_combatant() end})
	end,

	update_display = function(self)
		for i, v in ipairs(self.display) do gui.delete_node(v.node) end
		self.display = {}
		local active_i = utils.findIndex(self.to_deploy, self.active_id, 'id', 1)
		for i, combatant in ipairs(self.to_deploy) do
			local combatant_data = Combatant.get_data(combatant.prototype)
			if combatant.id == self.active_id then
				-- render the active party member
				local art = gui.get_node('active_combatant_art')
				gui.set_texture(art, 'combatants')
				gui_utils.set_texture_with_default_placeholder(art, 'combatants', combatant_data.idle_animation, '_placeholder')
				self.active_display.bar.set_max(combatant.max_hp)
				self.active_display.bar.set_fill(combatant.hp)
			else
				-- render the non-active party members on bar
				local template = gui.get_node('combatant_card_template')
				local tree = gui.clone_tree(template)
				local node = tree.combatant_card_template
				local art = tree.combatant_card_template_art
				gui.set_texture(node, 'combatants')
				if combatant_data.idle_animation then
					gui.play_flipbook(art, combatant_data.idle_animation)
				end
				local bar = bars.new(tree.combatant_card_template_hp, tree.combatant_card_template_hp_fill, nil, combatant.hp, combatant.max_hp)

				table.insert(self.display, {node=node, id=combatant.id})
				local i_mod = 0 if active_i and i > active_i then i_mod = -1 end -- account for active_combatant being pulled out of the bar
				local x = (i + i_mod) * 110
				gui.set_position(node, vmath.vector3(x, 0, 0))
				gui.set_parent(node, gui.get_node('combatants'))
			end
		end

		gui.set_enabled(gui.get_node('active_combatant'), #self.to_deploy > 0)
	end,

	active_combatant = nil,
	select_combatant = function(self, id) self.active_id = id end,
	place_combatant = function(self, id, position)
		local party_member = utils.search(self.to_deploy, function(v) return v.id == id end)
		party_member.position = position
		Battle.add_combatant(party_member)
		msg.post(urls.battle_proxy, 'combatant_added', {combatant = party_member})
		table.remove(self.to_deploy, 1)
		if #self.to_deploy > 0 then
			self.active_id = self.to_deploy[1].id
		else
			self.active_id = nil
		end
		self:update_display()
	end,
	undo_place_combatant = function(self)
		local combatant = Battle.undo_add_combatant()
		if not combatant then return end
		table.insert(self.to_deploy, 1, combatant)
		self.active_id = combatant.id
		self:update_display()
		msg.post(urls.battle_proxy, 'combatant_removed', {combatant = combatant})
	end,
	close = function(self)
		gui.set_enabled(gui.get_node('root'), false)
		for i, v in ipairs(self.display) do gui.delete_node(v.node) end
	end
}

function init(self)
	msg.post(urls.battle, 'acquire_input_focus')
	msg.post('.', 'acquire_input_focus')
	mygui = gui_module.new(self, {})

	Map:init()
	Deployment:init()
end

function on_input(self, action_id, action)
	mygui.handle_input(action_id, action)
end
